from .test_atic import TestATICHealth
from .test_basegov import TestBaseGovHealth
from .test_bpstat import TestBPstatHealth
from .test_commodities import TestCommoditiesHealth
from .test_eu_oil_bulletin import TestEUOilBulletinHealth
from .test_ine import TestINEHealth
from .test_ipma import TestIPMAHealth
from .test_omie import TestOMIEHealth
from .test_summary import TestHealthSummary
