title = "RAGLite gitleaks config"

[[rules]]
description = "Generic API Key"
id = "generic-api-key"
regex = '''(?i)(?:key|api[^Version]|token|secret|password)[\s]*[=:>]{1,3}[\s]*["']?([0-9a-zA-Z\-_]{20,})["']?'''
[rules.allowlist]
paths = [
    '''tests/unit/test_shared_config\.py''',
    '''tests/unit/test_shared_clients\.py''',
]
regexes = [
    '''test-key-abc123''',
    '''valid-api-key-abc123''',
]
