"""
Epic 3 P0 Critical Test Scenarios
==================================

Test templates for Epic 3: AI Intelligence Orchestration
Priority: P0 (Critical - must pass for release)

Stories Covered:
- Story 3.1: Agentic Framework Integration
- Story 3.2: Retrieval Agent Implementation
- Story 3.3: Analysis Agent Implementation
- Story 3.4: Synthesis Agent Implementation
- Story 3.5: Multi-Step Workflow Orchestration
- Story 3.6: Analytical Query Tool (MCP)
- Story 3.7: Graceful Degradation
- Story 3.8: Agentic Workflow Test Suite

Risk Coverage:
- R-001: Workflow timeout >30s (CRITICAL - score=9)
- R-002: Workflow success rate <80% (HIGH - score=6)
- R-003: Task decomposition failures (HIGH - score=6)
- R-006: Agent state management bugs (HIGH - score=6)

Generated by: BMad TEA Agent (Murat)
Date: 2025-11-05
"""

import pytest

# Epic 3 imports (TODO: Update paths when modules are implemented)
# from raglite.agentic.orchestration import execute_workflow_with_timeout
# from raglite.agentic.agents import RetrievalAgent, AnalysisAgent, SynthesisAgent
# from raglite.agentic.models import WorkflowPlan, AgentResult, AnalysisResult
# from raglite.main import analytical_query_tool, AnalyticalQueryRequest, AnalyticalQueryResponse
# Epic 1-2 imports (existing dependencies)

# ============================================================================
# Story 3.1: Agentic Framework Integration (P0 Tests)
# ============================================================================


@pytest.mark.skip(reason="Epic 3 Story 3.1 not yet implemented - LangGraph integration pending")
@pytest.mark.p0
@pytest.mark.integration
@pytest.mark.asyncio
class TestStory31FrameworkIntegration:
    """Story 3.1 P0: Framework initialization and basic workflow execution."""

    async def test_3_1_unit_001_langgraph_initializes_with_valid_state_schema(self):
        """
        Test ID: 3.1-UNIT-001
        Priority: P0
        Risk Link: R-001, R-006

        Validates LangGraph initializes correctly with WorkflowPlan state schema.
        This is the foundation for all agentic workflows.
        """
        # TODO: Uncomment when LangGraph integration complete (Story 3.1)
        pytest.skip("Story 3.1 not yet implemented - LangGraph integration pending")

        # from raglite.agentic.orchestration import WorkflowOrchestrator
        # from raglite.agentic.models import WorkflowPlan

        # # Arrange: Create orchestrator
        # orchestrator = WorkflowOrchestrator()

        # # Act: Initialize with valid state schema
        # workflow_plan = WorkflowPlan(
        #     id="test-workflow-001",
        #     original_query="Calculate revenue growth",
        #     steps=[
        #         {"agent": "retrieval", "task": "Retrieve Q3 2023 revenue"},
        #         {"agent": "synthesis", "task": "Synthesize answer"},
        #     ],
        # )

        # # Assert: LangGraph graph initializes without errors
        # graph = orchestrator.create_graph(workflow_plan)
        # assert graph is not None
        # assert graph.nodes is not None
        # assert len(graph.nodes) >= 2  # At least retrieval + synthesis nodes

    async def test_3_1_int_001_basic_2_step_workflow_executes_successfully(self):
        """
        Test ID: 3.1-INT-001
        Priority: P0 (SMOKE TEST)
        Risk Link: R-001, R-003

        Validates simplest possible workflow: Retrieve → Synthesize.
        This is the foundation workflow that all complex workflows build upon.

        Expected workflow:
        1. Retrieve relevant documents (5s)
        2. Synthesize answer from retrieved content (5s)
        Total: ~10s (well under 30s NFR5 target)
        """
        # TODO: Uncomment when Stories 3.1-3.4 complete
        pytest.skip("Stories 3.1-3.4 not yet implemented")

        # from raglite.main import analytical_query_tool, AnalyticalQueryRequest

        # # Arrange: Simple query requiring 2-step workflow
        # query = "What was the total revenue in Q3 2024?"
        # request = AnalyticalQueryRequest(query=query)

        # # Act: Execute workflow
        # start_time = time.perf_counter()
        # response = await analytical_query_tool(request)
        # execution_time_ms = (time.perf_counter() - start_time) * 1000

        # # Assert: Workflow completes successfully
        # assert response.workflow_status == "success"
        # assert response.answer is not None
        # assert len(response.answer) > 0
        # assert len(response.citations) > 0
        # assert execution_time_ms < 30000, f"Workflow exceeded 30s: {execution_time_ms:.0f}ms"

        # # Assert: Reasoning steps logged
        # assert len(response.reasoning_steps) >= 2  # Retrieve + Synthesize
        # assert any("retrieve" in step.lower() for step in response.reasoning_steps)
        # assert any("synthesize" in step.lower() for step in response.reasoning_steps)

        # print(f"✅ Basic 2-step workflow: {execution_time_ms:.0f}ms")

    @pytest.mark.timeout(35)  # 30s workflow + 5s test overhead
    async def test_3_1_int_002_workflow_timeout_handler_triggers_at_30s(self):
        """
        Test ID: 3.1-INT-002
        Priority: P0
        Risk Link: R-001 (CRITICAL - score=9)

        Validates workflow timeout enforcement with Epic 1 fallback.
        Critical for NFR5 <30s performance requirement.

        Simulates slow agent execution and verifies:
        1. Timeout triggers at 25s (5s buffer for fallback)
        2. Epic 1 fallback returns results within 30s total
        3. User receives partial results instead of error
        """
        # TODO: Uncomment when Story 3.7 (graceful degradation) complete
        pytest.skip("Story 3.7 not yet implemented - timeout handling pending")

        # from raglite.main import analytical_query_tool, AnalyticalQueryRequest
        # from raglite.agentic.agents import AnalysisAgent

        # # Arrange: Mock slow Analysis agent (26s execution)
        # with patch('raglite.agentic.agents.AnalysisAgent.execute') as mock_analysis:
        #     async def slow_analysis(*args, **kwargs):
        #         await asyncio.sleep(26)  # Exceeds 25s workflow timeout
        #         return AnalysisResult(metric="YoY", value=0.15)

        #     mock_analysis.side_effect = slow_analysis

        #     query = "Calculate revenue growth year-over-year"
        #     request = AnalyticalQueryRequest(query=query)

        #     # Act: Execute workflow with slow agent
        #     start_time = time.perf_counter()
        #     response = await analytical_query_tool(request)
        #     execution_time_ms = (time.perf_counter() - start_time) * 1000

        #     # Assert: Timeout fallback triggered
        #     assert response.workflow_status == "timeout_fallback"
        #     assert 25000 <= execution_time_ms <= 30000, (
        #         f"Timeout not in expected window: {execution_time_ms:.0f}ms"
        #     )

        #     # Assert: Fallback returned results (Epic 1)
        #     assert response.answer is not None
        #     assert len(response.citations) > 0
        #     assert any("timeout" in step.lower() for step in response.reasoning_steps)

        #     print(f"✅ Timeout fallback triggered: {execution_time_ms:.0f}ms")


# ============================================================================
# Story 3.2: Retrieval Agent Implementation (P0 Tests)
# ============================================================================


@pytest.mark.skip(reason="Epic 3 Story 3.2 not yet implemented - Retrieval agent pending")
@pytest.mark.p0
@pytest.mark.integration
@pytest.mark.asyncio
class TestStory32RetrievalAgent:
    """Story 3.2 P0: Retrieval agent integrates with Epic 1 search logic."""

    async def test_3_2_int_001_retrieval_agent_integrates_with_epic1_search(self):
        """
        Test ID: 3.2-INT-001
        Priority: P0
        Risk Link: R-003

        Validates Retrieval Agent successfully delegates to Epic 1 search.py.
        Critical dependency - Epic 3 builds on Epic 1 retrieval logic.

        Expected behavior:
        1. Retrieval agent receives query
        2. Delegates to search_documents() from Epic 1
        3. Returns QueryResult in AgentResult format
        4. Maintains Epic 1's 97.9% accuracy baseline
        """
        # TODO: Uncomment when Story 3.2 complete
        pytest.skip("Story 3.2 not yet implemented - Retrieval agent pending")

        # from raglite.agentic.agents import RetrievalAgent
        # from raglite.agentic.models import AgentResult

        # # Arrange: Retrieval agent with known query
        # agent = RetrievalAgent()
        # query = "What was Q3 2024 revenue?"

        # # Act: Execute retrieval
        # result = await agent.execute(query)

        # # Assert: AgentResult format
        # assert isinstance(result, AgentResult)
        # assert result.agent_type == "retrieval"
        # assert result.success is True
        # assert result.data is not None

        # # Assert: Epic 1 integration
        # assert "chunks" in result.data or "documents" in result.data
        # assert len(result.data.get("chunks", [])) > 0

        # # Assert: Citations included (NFR7 source attribution)
        # assert "citations" in result.data
        # assert len(result.data["citations"]) > 0


# ============================================================================
# Story 3.3: Analysis Agent Implementation (P0 Tests)
# ============================================================================


@pytest.mark.skip(reason="Epic 3 Story 3.3 not yet implemented - Analysis agent pending")
@pytest.mark.p0
@pytest.mark.unit
class TestStory33AnalysisAgent:
    """Story 3.3 P0: Financial calculation accuracy validation."""

    def test_3_3_unit_001_analysis_agent_calculates_yoy_growth_correctly(self):
        """
        Test ID: 3.3-UNIT-001
        Priority: P0 (SMOKE TEST)
        Risk Link: R-002

        Validates Year-over-Year growth calculation accuracy.
        Core financial metric - must be mathematically correct.

        Formula: YoY Growth = ((Current - Previous) / Previous) * 100
        """
        # TODO: Uncomment when Story 3.3 complete
        pytest.skip("Story 3.3 not yet implemented - Analysis agent pending")

        # from raglite.agentic.agents import AnalysisAgent
        # from raglite.agentic.models import AnalysisTask

        # # Arrange: Known financial data
        # agent = AnalysisAgent()
        # task = AnalysisTask(
        #     metric="yoy_growth",
        #     current_value=120_000_000,  # Q3 2024: $120M
        #     previous_value=100_000_000,  # Q3 2023: $100M
        # )

        # # Act: Calculate YoY growth
        # result = agent.calculate_yoy_growth(task)

        # # Assert: Correct calculation
        # expected_growth = ((120 - 100) / 100) * 100  # 20% growth
        # assert abs(result.value - expected_growth) < 0.01, (
        #     f"YoY calculation error: expected {expected_growth}%, got {result.value}%"
        # )
        # assert result.metric == "yoy_growth"
        # assert result.unit == "percentage"

    def test_3_3_unit_002_analysis_agent_calculates_variance_correctly(self):
        """
        Test ID: 3.3-UNIT-002
        Priority: P0
        Risk Link: R-002

        Validates variance calculation accuracy.
        Important for comparing actual vs forecast, budget vs actual, etc.

        Formula: Variance = Actual - Expected
        """
        # TODO: Uncomment when Story 3.3 complete
        pytest.skip("Story 3.3 not yet implemented")

        # from raglite.agentic.agents import AnalysisAgent
        # from raglite.agentic.models import AnalysisTask

        # # Arrange: Actual vs forecast data
        # agent = AnalysisAgent()
        # task = AnalysisTask(
        #     metric="variance",
        #     actual_value=115_000_000,   # Actual Q3 2024: $115M
        #     expected_value=120_000_000,  # Forecast Q3 2024: $120M
        # )

        # # Act: Calculate variance
        # result = agent.calculate_variance(task)

        # # Assert: Correct calculation
        # expected_variance = 115 - 120  # -$5M (unfavorable)
        # assert abs(result.value - expected_variance) < 0.01
        # assert result.metric == "variance"
        # assert result.unit == "dollars_millions"


@pytest.mark.skip(
    reason="Epic 3 Story 3.3 not yet implemented - Analysis agent LLM integration pending"
)
@pytest.mark.p0
@pytest.mark.integration
@pytest.mark.asyncio
class TestStory33AnalysisAgentIntegration:
    """Story 3.3 P0: Analysis agent numerical accuracy with LLM."""

    async def test_3_3_int_003_analysis_agent_numerical_accuracy_validation(self):
        """
        Test ID: 3.3-INT-003
        Priority: P0
        Risk Link: R-002

        Validates Analysis Agent achieves ≤0.01% numerical error when using LLM.
        Critical for financial calculations - errors compound in multi-step workflows.

        Tests Claude Haiku's ability to perform accurate calculations.
        """
        # TODO: Uncomment when Story 3.3 complete
        pytest.skip("Story 3.3 not yet implemented - LLM integration pending")

        # from raglite.agentic.agents import AnalysisAgent
        # from raglite.agentic.models import AnalysisTask

        # # Arrange: Analysis agent with LLM backend
        # agent = AnalysisAgent()  # Uses Claude Haiku
        # task = AnalysisTask(
        #     metric="yoy_growth",
        #     instruction="Calculate year-over-year revenue growth from $100M to $125M",
        #     current_value=125_000_000,
        #     previous_value=100_000_000,
        # )

        # # Act: Execute via LLM
        # result = await agent.execute(task)

        # # Assert: Accurate calculation (25% growth)
        # expected_growth = 25.0
        # error_percent = abs((result.value - expected_growth) / expected_growth) * 100
        # assert error_percent <= 0.01, (
        #     f"LLM calculation error too high: {error_percent:.4f}% (max: 0.01%)"
        # )


# ============================================================================
# Story 3.4: Synthesis Agent Implementation (P0 Tests)
# ============================================================================


@pytest.mark.skip(reason="Epic 3 Story 3.4 not yet implemented - Synthesis agent pending")
@pytest.mark.p0
@pytest.mark.unit
class TestStory34SynthesisAgent:
    """Story 3.4 P0: Citation attribution in synthesis output."""

    def test_3_4_unit_002_synthesis_includes_all_source_citations(self):
        """
        Test ID: 3.4-UNIT-002
        Priority: P0
        Risk Link: NFR7 (source attribution requirement)

        Validates Synthesis Agent includes all citations from upstream agents.
        Critical for compliance, transparency, and user trust.

        NFR7: ≥95% attribution accuracy
        """
        # TODO: Uncomment when Story 3.4 complete
        pytest.skip("Story 3.4 not yet implemented - Synthesis agent pending")

        # from raglite.agentic.agents import SynthesisAgent
        # from raglite.agentic.models import AgentResult

        # # Arrange: Multi-source results with citations
        # agent = SynthesisAgent()
        # upstream_results = [
        #     AgentResult(
        #         agent_type="retrieval",
        #         success=True,
        #         data={
        #             "chunks": ["Q3 2024 revenue was $120M"],
        #             "citations": ["doc_456.pdf:page_12"],
        #         },
        #     ),
        #     AgentResult(
        #         agent_type="analysis",
        #         success=True,
        #         data={
        #             "metric": "yoy_growth",
        #             "value": 20.0,
        #             "citations": ["calculated_from:doc_456.pdf:page_12,doc_123.pdf:page_8"],
        #         },
        #     ),
        # ]

        # # Act: Synthesize answer
        # result = agent.synthesize(
        #     query="What was Q3 2024 revenue and YoY growth?",
        #     agent_results=upstream_results,
        # )

        # # Assert: All citations included
        # expected_citations = ["doc_456.pdf:page_12", "doc_123.pdf:page_8"]
        # for citation in expected_citations:
        #     assert citation in result.citations, (
        #         f"Missing citation: {citation}"
        #     )


# ============================================================================
# Story 3.5: Multi-Step Workflow Orchestration (P0 Tests)
# ============================================================================


@pytest.mark.skip(reason="Epic 3 Story 3.5 not yet implemented - Workflow orchestration pending")
@pytest.mark.p0
@pytest.mark.unit
class TestStory35WorkflowOrchestration:
    """Story 3.5 P0: Query classification and task decomposition."""

    def test_3_5_unit_001_planner_classifies_simple_vs_analytical_queries(self):
        """
        Test ID: 3.5-UNIT-001
        Priority: P0 (SMOKE TEST)
        Risk Link: R-003

        Validates query classification logic.
        Critical routing decision - simple queries go to Epic 1 (fast), analytical to Epic 3.

        SIMPLE: Direct factual queries (who, what, when, where)
        ANALYTICAL: Calculations, trends, comparisons, forecasts (how much, compare, trend)
        """
        # TODO: Uncomment when Story 3.5 complete
        pytest.skip("Story 3.5 not yet implemented - Planner logic pending")

        # from raglite.agentic.orchestration import QueryPlanner

        # # Arrange: Planner with test queries
        # planner = QueryPlanner()

        # # Act & Assert: Simple queries
        # simple_queries = [
        #     "What was Q3 2024 revenue?",
        #     "Who is the CEO?",
        #     "When was the company founded?",
        # ]
        # for query in simple_queries:
        #     classification = planner.classify_query(query)
        #     assert classification == "SIMPLE", (
        #         f"Misclassified simple query: {query} → {classification}"
        #     )

        # # Act & Assert: Analytical queries
        # analytical_queries = [
        #     "Calculate year-over-year revenue growth",
        #     "Compare Q3 2023 and Q3 2024 performance",
        #     "What is the trend in operating expenses?",
        #     "How much did revenue increase from last quarter?",
        # ]
        # for query in analytical_queries:
        #     classification = planner.classify_query(query)
        #     assert classification == "ANALYTICAL", (
        #         f"Misclassified analytical query: {query} → {classification}"
        #     )

    def test_3_5_unit_002_planner_decomposes_complex_query_into_subtasks(self):
        """
        Test ID: 3.5-UNIT-002
        Priority: P0
        Risk Link: R-003

        Validates task decomposition logic.
        Critical for workflow execution - incorrect decomposition causes failures.

        Example decomposition:
        Query: "Calculate YoY revenue growth"
        Steps:
        1. Retrieve current period revenue (Q3 2024)
        2. Retrieve previous period revenue (Q3 2023)
        3. Calculate YoY growth percentage
        4. Synthesize answer with citations
        """
        # TODO: Uncomment when Story 3.5 complete
        pytest.skip("Story 3.5 not yet implemented")

        # from raglite.agentic.orchestration import QueryPlanner
        # from raglite.agentic.models import WorkflowPlan

        # # Arrange: Planner with complex analytical query
        # planner = QueryPlanner()
        # query = "Calculate year-over-year revenue growth between Q3 2023 and Q3 2024"

        # # Act: Decompose into workflow steps
        # workflow_plan = planner.decompose_query(query)

        # # Assert: Valid WorkflowPlan structure
        # assert isinstance(workflow_plan, WorkflowPlan)
        # assert workflow_plan.original_query == query
        # assert len(workflow_plan.steps) >= 3  # At minimum: retrieve, analyze, synthesize

        # # Assert: Expected step sequence
        # step_types = [step["agent"] for step in workflow_plan.steps]
        # assert "retrieval" in step_types  # Must retrieve data
        # assert "analysis" in step_types   # Must calculate YoY
        # assert "synthesis" in step_types  # Must synthesize answer

        # # Assert: Step instructions are specific
        # for step in workflow_plan.steps:
        #     assert "task" in step
        #     assert len(step["task"]) > 10  # Not empty/generic


@pytest.mark.skip(
    reason="Epic 3 Story 3.5 not yet implemented - Workflow performance validation pending"
)
@pytest.mark.p0
@pytest.mark.integration
@pytest.mark.asyncio
@pytest.mark.timeout(35)
class TestStory35WorkflowPerformance:
    """Story 3.5 P0: Workflow performance validation."""

    async def test_3_5_int_001_yoy_variance_workflow_under_30s(self):
        """
        Test ID: 3.5-INT-001
        Priority: P0
        Risk Link: R-001 (CRITICAL - score=9)

        Validates 5-step analytical workflow completes within NFR5 30s target.
        This is the GATE BLOCKER test - Epic 3 cannot ship if this fails.

        Workflow: Planner → Retrieve (Q3 2023) → Retrieve (Q3 2024) → Analyze → Synthesize
        Expected: 14-19s typical, <30s p95

        Validates R-001 mitigation:
        - Parallel retrieval (2 concurrent searches)
        - Claude Haiku for analysis (faster than Sonnet)
        - Timeout enforcement (25s limit + 5s fallback buffer)
        """
        # TODO: Uncomment when Story 3.5 complete
        pytest.skip("Story 3.5 not yet implemented - full orchestration pending")

        # from raglite.main import analytical_query_tool, AnalyticalQueryRequest

        # # Arrange: Complex 5-step analytical query
        # query = "Calculate year-over-year revenue growth variance between Q3 2023 and Q3 2024"
        # request = AnalyticalQueryRequest(query=query)

        # # Act: Execute full workflow
        # start_time = time.perf_counter()
        # response = await analytical_query_tool(request)
        # execution_time_ms = (time.perf_counter() - start_time) * 1000

        # # Assert: Performance target met (CRITICAL)
        # assert execution_time_ms < 30000, (
        #     f"🔴 GATE BLOCKER: Workflow exceeded NFR5 30s target: {execution_time_ms:.0f}ms"
        # )

        # # Assert: Answer is correct (not just fast)
        # assert response.workflow_status == "success"
        # assert response.answer is not None
        # assert "growth" in response.answer.lower()
        # assert len(response.citations) > 0

        # # Assert: Workflow steps logged
        # assert len(response.reasoning_steps) >= 4  # Planner, Retrieve x2, Analyze, Synthesize

        # print(f"✅ 5-step workflow: {execution_time_ms:.0f}ms (target: <30000ms)")


# ============================================================================
# Story 3.8: Agentic Workflow Test Suite (P0 Tests)
# ============================================================================


@pytest.mark.skip(reason="Epic 3 Story 3.8 not yet implemented - Workflow test suite pending")
@pytest.mark.p0
@pytest.mark.integration
@pytest.mark.asyncio
class TestStory38WorkflowTestSuite:
    """Story 3.8 P0: Success rate validation (Epic 3 completion gate)."""

    async def test_3_8_int_001_execute_15plus_analytical_queries_from_ground_truth(
        self, load_ground_truth_analytical
    ):
        """
        Test ID: 3.8-INT-001
        Priority: P0
        Risk Link: R-002 (Epic 3 completion gate)

        Executes all analytical queries from ground_truth_analytical.json.
        Validates workflow execution across diverse analytical patterns.

        Prerequisites:
        - tests/fixtures/ground_truth_analytical.json exists (15+ Q&A pairs)
        - All Epic 3 stories (3.1-3.7) complete
        """
        # TODO: Uncomment when Story 3.8 complete
        pytest.skip("Story 3.8 not yet implemented - ground truth dataset pending")

        # from raglite.main import analytical_query_tool, AnalyticalQueryRequest

        # # Arrange: Load ground truth analytical queries
        # test_queries = load_ground_truth_analytical  # Fixture provides 15+ queries
        # assert len(test_queries) >= 15, "Ground truth must have 15+ analytical queries"

        # results = []

        # # Act: Execute all queries
        # for test_case in test_queries:
        #     query = test_case["query"]
        #     expected_answer_keywords = test_case.get("expected_keywords", [])

        #     try:
        #         response = await analytical_query_tool(
        #             AnalyticalQueryRequest(query=query)
        #         )
        #         results.append({
        #             "query": query,
        #             "success": response.workflow_status == "success",
        #             "answer": response.answer,
        #             "execution_time_ms": response.execution_time_ms,
        #         })
        #     except Exception as e:
        #         results.append({
        #             "query": query,
        #             "success": False,
        #             "error": str(e),
        #         })

        # # Log results for analysis
        # successful = [r for r in results if r["success"]]
        # print(f"\n📊 Analytical Query Execution Results:")
        # print(f"Total queries: {len(results)}")
        # print(f"Successful: {len(successful)}")
        # print(f"Failed: {len(results) - len(successful)}")

        # # Individual query results
        # for i, result in enumerate(results, 1):
        #     status = "✅" if result["success"] else "❌"
        #     print(f"{status} {i}. {result['query'][:60]}...")

    async def test_3_8_int_002_workflow_success_rate_meets_80_percent_target(
        self, load_ground_truth_analytical
    ):
        """
        Test ID: 3.8-INT-002
        Priority: P0
        Risk Link: R-002 (EPIC 3 COMPLETION GATE)

        Validates workflow success rate ≥80% on ground truth analytical queries.
        This is the FINAL GATE - Epic 3 cannot be marked COMPLETE until this passes.

        Success criteria (per AC 3.8.3):
        - Success rate ≥80% on 15+ analytical queries
        - Failures documented in docs/epic-3-failure-analysis.md
        """
        # TODO: Uncomment when Story 3.8 complete
        pytest.skip("Story 3.8 not yet implemented - success rate validation pending")

        # from raglite.main import analytical_query_tool, AnalyticalQueryRequest

        # # Arrange: Load ground truth analytical queries
        # test_queries = load_ground_truth_analytical
        # assert len(test_queries) >= 15

        # results = []

        # # Act: Execute all queries
        # for test_case in test_queries:
        #     query = test_case["query"]

        #     try:
        #         response = await analytical_query_tool(
        #             AnalyticalQueryRequest(query=query)
        #         )
        #         success = response.workflow_status == "success"
        #         results.append({"query": query, "success": success})
        #     except Exception as e:
        #         results.append({"query": query, "success": False, "error": str(e)})

        # # Calculate success rate
        # successful = [r for r in results if r["success"]]
        # success_rate = (len(successful) / len(results)) * 100

        # # Log detailed results
        # print(f"\n📊 Epic 3 Success Rate Validation:")
        # print(f"Total queries: {len(results)}")
        # print(f"Successful: {len(successful)}")
        # print(f"Success rate: {success_rate:.1f}%")
        # print(f"Target: ≥80%")

        # # Assert: EPIC 3 COMPLETION GATE
        # assert success_rate >= 80.0, (
        #     f"🔴 EPIC 3 BLOCKED: Success rate {success_rate:.1f}% below 80% target. "
        #     f"Review docs/epic-3-failure-analysis.md for failure patterns."
        # )

        # print(f"✅ Epic 3 completion gate PASSED: {success_rate:.1f}% success rate")


# ============================================================================
# Pytest Fixtures
# ============================================================================


@pytest.fixture
def load_ground_truth_analytical():
    """
    Load analytical queries from tests/fixtures/ground_truth_analytical.json.

    Expected format:
    [
        {
            "query": "Calculate year-over-year revenue growth between Q3 2023 and Q3 2024",
            "expected_answer": "Revenue grew 20% year-over-year...",
            "expected_keywords": ["20%", "growth", "Q3 2023", "Q3 2024"],
            "category": "yoy_analysis"
        },
        ...
    ]
    """
    import json
    from pathlib import Path

    fixture_path = Path(__file__).parent.parent / "fixtures" / "ground_truth_analytical.json"

    if not fixture_path.exists():
        pytest.skip(f"Ground truth analytical dataset not found: {fixture_path}")

    with open(fixture_path) as f:
        data = json.load(f)

    return data


# ============================================================================
# Test Collection & Reporting
# ============================================================================


def pytest_collection_modifyitems(config, items):
    """
    Automatically mark tests with appropriate markers for selective execution.

    Usage:
    - pytest -m p0                    # Run only P0 critical tests
    - pytest -m "p0 and unit"         # Run P0 unit tests only
    - pytest -m "p0 and integration"  # Run P0 integration tests only
    """
    for item in items:
        # Add story markers
        if "test_story_31" in item.nodeid.lower():
            item.add_marker(pytest.mark.story_3_1)
        elif "test_story_32" in item.nodeid.lower():
            item.add_marker(pytest.mark.story_3_2)
        elif "test_story_33" in item.nodeid.lower():
            item.add_marker(pytest.mark.story_3_3)
        elif "test_story_34" in item.nodeid.lower():
            item.add_marker(pytest.mark.story_3_4)
        elif "test_story_35" in item.nodeid.lower():
            item.add_marker(pytest.mark.story_3_5)
        elif "test_story_38" in item.nodeid.lower():
            item.add_marker(pytest.mark.story_3_8)
