"""Metadata storage operations for PostgreSQL database.

Handles chunk metadata storage in the financial_chunks table.
"""

from __future__ import annotations

import time
import uuid
from datetime import datetime
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass

from psycopg2.extras import execute_values

from raglite.shared.clients import get_postgresql_connection
from raglite.shared.logging import get_logger
from raglite.shared.models import Chunk
from raglite.shared.safety import SafetyGuard

logger = get_logger(__name__)

# Story 4.0.6: SafetyGuard instance for environment audit logging
_guard = SafetyGuard()


async def store_metadata_in_postgresql(
    chunks: list[Chunk], batch_size: int = 100
) -> tuple[int, int]:
    """Store chunk metadata in PostgreSQL for structured filtering (Story 2.6 AC4).

    Only stores chunks that have extracted metadata. Chunks without metadata are skipped
    with a debug log entry.

    Args:
        chunks: List of Chunk objects with optional extracted metadata
        batch_size: Records per batch (default: 100 for memory efficiency)

    Returns:
        Tuple of (records_stored, records_skipped)

    Raises:
        RuntimeError: If PostgreSQL storage fails

    Example:
        >>> stored, skipped = await store_metadata_in_postgresql(chunks)
        >>> logger.info(f"Stored {stored} chunks, skipped {skipped} without metadata")
    """
    start_time = time.time()

    # Story 4.0.6: Log environment for audit trail
    _guard.log_operation("store_metadata_postgresql")
    logger.info(
        "Storing metadata in PostgreSQL",
        extra={
            "chunk_count": len(chunks),
            "batch_size": batch_size,
            "environment": "PRODUCTION" if _guard.is_production else "TEST",
        },
    )

    if not chunks:
        logger.warning("No chunks provided for PostgreSQL storage")
        return (0, 0)

    # CRITICAL FIX (CI): Store ALL chunks, not just those with extracted metadata
    # Metadata fields are nullable by design (see migrations/002_create_financial_tables.sql)
    # Previously filtered to only chunks with metadata, causing 0 chunks to be stored when
    # MISTRAL_API_KEY is not configured (CI environment, parallel ingestion tests)
    #
    # Root cause: Tests in tests/integration/test_parallel_ingestion.py were failing with:
    # - AssertionError: New chunks should be stored in PostgreSQL financial_chunks
    # - Assert: 0 > 0
    #
    # This was because metadata extraction requires MISTRAL_API_KEY, which is not set in CI.
    # Without metadata, all chunks were being skipped, resulting in empty PostgreSQL table.
    #
    # Fix: Store all chunks regardless of metadata presence. Metadata is optional enrichment.
    chunks_to_store = chunks
    chunks_with_metadata_count = sum(
        1 for chunk in chunks if chunk.document_type or chunk.company_name or chunk.metric_category
    )

    logger.info(
        "Preparing chunks for PostgreSQL storage",
        extra={
            "total_chunks": len(chunks),
            "with_metadata": chunks_with_metadata_count,
            "without_metadata": len(chunks) - chunks_with_metadata_count,
        },
    )

    try:
        conn = get_postgresql_connection()
        cursor = conn.cursor()

        # Prepare records for batch insert
        records = []
        for chunk in chunks_to_store:
            # Generate new UUID for PostgreSQL chunk_id (primary key)
            # Use chunk.chunk_id as STRING for embedding_id (link to Qdrant vector)
            record = (
                uuid.uuid4(),  # chunk_id: NEW UUID for PostgreSQL primary key
                chunk.metadata.filename,  # document_id: use source document filename
                chunk.page_number,
                chunk.chunk_index,
                chunk.content,
                # Document-Level Metadata (7 fields)
                chunk.document_type,
                chunk.reporting_period,
                chunk.time_granularity,
                chunk.company_name,
                chunk.geographic_jurisdiction,
                chunk.data_source_type,
                chunk.version_date,
                # Section-Level Metadata (5 fields)
                chunk.section_type,
                chunk.metric_category,
                chunk.units,
                chunk.department_scope,
                # Table-Specific Metadata (3 fields)
                chunk.table_context,
                chunk.table_name,
                chunk.statistical_summary,
                # Search optimization
                None,  # content_tsv (will be generated by trigger)
                chunk.chunk_id,  # embedding_id (VARCHAR - link to Qdrant vector ID as STRING)
                datetime.now(),  # created_at
                datetime.now(),  # updated_at
            )
            records.append(record)

        # Insert in batches
        total_batches = (len(records) + batch_size - 1) // batch_size

        for i in range(0, len(records), batch_size):
            batch_num = (i // batch_size) + 1
            batch_records = records[i : i + batch_size]

            logger.info(
                f"Uploading PostgreSQL batch {batch_num}/{total_batches}",
                extra={
                    "batch_num": batch_num,
                    "batch_size": len(batch_records),
                    "total_batches": total_batches,
                },
            )

            execute_values(
                cursor,
                """
                INSERT INTO financial_chunks (
                    chunk_id, document_id, page_number, chunk_index, content,
                    document_type, reporting_period, time_granularity, company_name,
                    geographic_jurisdiction, data_source_type, version_date,
                    section_type, metric_category, units, department_scope,
                    table_context, table_name, statistical_summary,
                    content_tsv, embedding_id, created_at, updated_at
                ) VALUES %s
                """,
                batch_records,
            )

        conn.commit()
        cursor.close()

        duration_ms = int((time.time() - start_time) * 1000)

        logger.info(
            "PostgreSQL metadata storage complete",
            extra={
                "records_stored": len(chunks_to_store),
                "with_metadata": chunks_with_metadata_count,
                "without_metadata": len(chunks_to_store) - chunks_with_metadata_count,
                "duration_ms": duration_ms,
                "records_per_second": (
                    round(len(chunks_to_store) / (duration_ms / 1000), 2) if duration_ms > 0 else 0
                ),
            },
        )

        return (len(chunks_to_store), 0)  # All chunks stored, none skipped

    except Exception as e:
        # Rollback the transaction to clean up the connection
        try:
            if "cursor" in locals() and cursor:
                cursor.close()
        except Exception:  # nosec B110 - Cleanup handler: errors are non-critical  # nosec B110 - Cleanup handler: cursor close errors are non-critical
            pass  # Cleanup handler: ignore cursor close errors

        try:
            conn.rollback()
        except Exception:  # nosec B110 - Cleanup handler: errors are non-critical  # nosec B110 - Cleanup handler: rollback errors are non-critical
            pass  # Cleanup handler: ignore rollback errors

        logger.error(
            "PostgreSQL metadata storage failed",
            extra={"error": str(e)},
            exc_info=True,
        )
        raise RuntimeError(f"Failed to store metadata in PostgreSQL: {e}") from e
