#!/usr/bin/env python3
"""Post coverage comment to PR using GitHub API.

Usage:
    python scripts/post_coverage_comment.py .coverage.json [--baseline .coverage-baseline.json]

Requires:
    - GITHUB_TOKEN environment variable
    - GITHUB_REPOSITORY environment variable
    - GITHUB_PR_NUMBER or GITHUB_REF_NAME environment variable
"""

import json
import os
import subprocess
import sys
from pathlib import Path


def get_pr_number() -> int | None:
    """Get PR number from GitHub Actions environment."""
    # Direct PR number (set by workflow)
    pr_number = os.environ.get("GITHUB_PR_NUMBER")
    if pr_number:
        return int(pr_number)

    # Extract from ref (refs/pull/123/merge)
    ref = os.environ.get("GITHUB_REF", "")
    if ref.startswith("refs/pull/"):
        parts = ref.split("/")
        if len(parts) >= 3:
            return int(parts[2])

    return None


def load_coverage(path: str) -> dict:
    """Load coverage JSON data."""
    with open(path) as f:
        return json.load(f)


def format_coverage_comment(current: dict, baseline: dict | None = None) -> str:
    """Format coverage data as markdown comment."""
    total_pct = current.get("totals", {}).get("percent_covered", 0)

    # Determine status emoji
    if total_pct >= 80:
        status = "🟢"
        status_text = "Coverage is good"
    elif total_pct >= 60:
        status = "🟡"
        status_text = "Coverage needs improvement"
    else:
        status = "🔴"
        status_text = "Coverage is below threshold"

    lines = [
        "## 📊 Coverage Report",
        "",
        f"**Overall Coverage:** {total_pct:.1f}% {status}",
        "",
    ]

    # Add comparison with baseline if available
    if baseline:
        baseline_pct = baseline.get("totals", {}).get("percent_covered", 0)
        diff = total_pct - baseline_pct
        if diff > 0:
            lines.append(f"📈 **Change:** +{diff:.1f}% from baseline ({baseline_pct:.1f}%)")
        elif diff < 0:
            lines.append(f"📉 **Change:** {diff:.1f}% from baseline ({baseline_pct:.1f}%)")
        else:
            lines.append(f"➡️ **Change:** No change from baseline ({baseline_pct:.1f}%)")
        lines.append("")

    # Coverage thresholds
    lines.extend(
        [
            "### Thresholds",
            f"- 🟢 **Green:** ≥80% (Current: {total_pct:.1f}%)",
            "- 🟡 **Orange:** ≥60%",
            "- 🔴 **Red:** <60%",
            "",
            f"**Status:** {status_text}",
            "",
        ]
    )

    # File breakdown (top 10 lowest coverage)
    files = current.get("files", {})
    if files:
        sorted_files = sorted(
            [(f, d.get("summary", {}).get("percent_covered", 0)) for f, d in files.items()],
            key=lambda x: x[1],
        )[:10]

        lines.extend(
            [
                "<details>",
                "<summary>📁 Files with lowest coverage (click to expand)</summary>",
                "",
                "| File | Coverage |",
                "|------|----------|",
            ]
        )
        for filepath, pct in sorted_files:
            short_path = filepath.replace("raglite/", "")
            lines.append(f"| `{short_path}` | {pct:.1f}% |")
        lines.extend(["", "</details>", ""])

    # Footer
    lines.extend(["---", "*Coverage report generated by RAGLite CI*"])

    return "\n".join(lines)


def post_comment(body: str, pr_number: int) -> None:
    """Post or update comment on PR using gh CLI."""
    repo = os.environ.get("GITHUB_REPOSITORY")
    if not repo:
        print("Error: GITHUB_REPOSITORY not set")
        sys.exit(1)

    # Unique marker to identify our comments
    marker = "<!-- coverage-comment-marker -->"
    body_with_marker = f"{marker}\n{body}"

    # Check for existing coverage comment
    result = subprocess.run(
        [
            "gh",
            "api",
            f"repos/{repo}/issues/{pr_number}/comments",
            "--jq",
            f'.[] | select(.body | contains("{marker}")) | .id',
        ],
        capture_output=True,
        text=True,
    )

    existing_id = result.stdout.strip().split("\n")[0] if result.stdout.strip() else None

    if existing_id:
        # Update existing comment
        print(f"Updating existing comment {existing_id}...")
        subprocess.run(
            [
                "gh",
                "api",
                "--method",
                "PATCH",
                f"repos/{repo}/issues/comments/{existing_id}",
                "-f",
                f"body={body_with_marker}",
            ],
            check=True,
        )
        print(f"✅ Updated coverage comment on PR #{pr_number}")
    else:
        # Create new comment
        print("Creating new comment...")
        subprocess.run(
            [
                "gh",
                "api",
                "--method",
                "POST",
                f"repos/{repo}/issues/{pr_number}/comments",
                "-f",
                f"body={body_with_marker}",
            ],
            check=True,
        )
        print(f"✅ Posted coverage comment on PR #{pr_number}")


def main() -> None:
    """Main entry point."""
    if len(sys.argv) < 2:
        print("Usage: post_coverage_comment.py <coverage.json> [--baseline <baseline.json>]")
        sys.exit(1)

    coverage_path = sys.argv[1]
    baseline_path = None

    # Parse --baseline argument
    if "--baseline" in sys.argv:
        idx = sys.argv.index("--baseline")
        if idx + 1 < len(sys.argv):
            baseline_path = sys.argv[idx + 1]

    # Load coverage data
    current = load_coverage(coverage_path)
    baseline = (
        load_coverage(baseline_path) if baseline_path and Path(baseline_path).exists() else None
    )

    # Get PR number
    pr_number = get_pr_number()
    if not pr_number:
        print("⚠️ Not a PR context - skipping comment")
        return

    # Format and post comment
    comment = format_coverage_comment(current, baseline)
    post_comment(comment, pr_number)


if __name__ == "__main__":
    main()
